#!/bin/bash
#
VERSION="0.1"
AUTHOR="Frederico Sales"
DATA="28/08/2021"
EMAIL="frederico.sales@uab.ufjf.br"
SNAM=$(basename "$0")
__VERSION__="
$SNAM version: $VERSION - $DATA
  Environment: CEAD - UFJF
--------------------------------
Author: $AUTHOR
E-mail: $EMAIL

"
__USAGE__="
           __
      w  c(..)o   (
       \__(-)    __)
           /\   (
          /(_)___)
          w /|
           | \\
          m  m

Usage: $SNAM [OPTIONS]
       $SNAM [-c] [-d]

Options:
    -h  - display this help
    -c  - use docker build  to build the image
    -d  - use docker-compose to build the swarm
    -v  - show the version

 Author: $AUTHOR
 E-mail: $EMAIL
Version: $VERSION - $DATA

"

ARGS=$(echo "$1" | awk '{print tolower($0)}')

case $ARGS in
	-h)
		# clear;
		printf "$__USAGE__";
        ;;

    -v)
        # clear;
        printf "$__VERSION__";
        ;;

	-d)
		# clear;
		echo "Building the service";
		docker build -t satangos/moodle:raw .;
		;;

	-c)
		# clear;
		echo "Building the service";
		docker-compose build .;
		;;
	*)
		# clear;
		printf  "$__USAGE__";
        exit 1;
		;;
esac
